### ISSUE TITLE
bean read_device_info does not show Software version

### ISSUE THREAD

**Issue by shuckle50** [PunchThrough/bean-sdk-node#2]
With version 0.3.1:

> $ bean read_device_info -a $A1
> 
> Found Bean with name/address: /987bf358352b
> Connected!
>       Manufacturer: Punch Through Design
>       Model Number: Bean+
>   Hardware Version: 2A
>   Firmware Version: 201608170000 Img-B
>   Software Version: Software Revision
>      Battery Level: 60%
>        Sketch Name: test3-bean-comditeng
> 
> 
> Command completed successfully
> 

I would have expected to see 0.3.1 instead of "Software Revision" ?

**Comment by swstack** [comment]
Hi @shuckle50 

The information shown in this command is about the Bean itself, not the software connecting to it. However, the Bean does not use a software version so the string `Software Revision` is just hardcoded in the Bean's firmware, for potential use at a later time. I could remove it to avoid confusion.

-Steve

**Comment by swstack** [comment]
I've removed Software Version from the output for now, will be in next release.
